# These are supported funding model platforms
liberapay: actumn # Replace with a single Liberapay username
custom: paypal.me/actumn # Replace with up to 4 custom sponsorship URLs e.g., ['link1', 'link2']
